# Generated by Django 4.0.6 on 2022-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('ApplicantId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Status', models.IntegerField()),
                ('Flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
    ]
